### ISSUE TITLE
Errors when Decrypting

### ISSUE THREAD

**Issue by Doodert** [odwdinc/SSBU_Amiibo#19]
Encountering the following output when attempting to Decrypt:

212
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "ssbu_amiibo\ui.py", line 293, in Decrypt
  File "ssbu_amiibo\ui.py", line 170, in handaleFile
  File "ssbu_amiibo\amiibo_class.py", line 47, in __init__
  File "ssbu_amiibo\amiibo_class.py", line 118, in GetWebData
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)

Have already performed fresh installs, reran all commands, attempted to use the old version with modifications etc.
It appears that Decrypting does work, as I can then open this file within the old version which pulls correct data showing Exp, Attack, Defense and Gift.

Only issue is I can't get the old version to detect my *.bin key files, so no Decrypt/Encrypt options available. 
It appears that the original post on GBATemp also has someone experiencing this issue as well; however, I am not super familiar with what I may be able to do to resolve it at this point.

Any help/assistance would be lovely.

**Comment by odwdinc** [comment]
https://github.com/odwdinc/SSBU_Amiibo/releases/tag/v0.0.5
